
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='evo-ingress',
    version='0.1.0',
    python_requires='==3.*,>=3.7.0',
    author='Moishe Keselman',
    author_email='team@evoeco.com',
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['argh==0.*,>=0.26.2', 'pyjwt==1.*,>=1.7.0', 'pyyaml==5.*,>=5.3.1', 'watchdog==1.*,>=1.0.2'],
)
