FROM andrewmk/rpi-kivy:stretch

#RUN apt-get update && apt-get install -yq --no-install-recommends \
#    gcc libraspberrypi-dev libraspberrypi-bin libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
#    pkg-config libgl1-mesa-dev libgles2-mesa-dev mtdev-tools\
#    python-pygame python-setuptools libgstreamer1.0-dev git-core \
#    gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
#    gstreamer1.0-alsa gstreamer1.0-omx python3-dev python3-pip && \
#    apt-get clean && rm -rf /var/lib/apt/lists/*
#
#RUN curl https://bootstrap.pypa.io/get-pip.py | python3
#
#RUN pip3 install wheel && pip3 install pgen && pip3 install -I Cython==0.29.10 && rm -Rf /root/.cache/*

RUN apt update && apt upgrade && apt-get install -y git vim python3-venv

#libs for kivy
RUN apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
RUN apt-get install -y pkg-config libgl1-mesa-dev libgles2-mesa-dev
RUN apt-get install -y python-setuptools libgstreamer1.0-dev git-core
#RUN apt-get install -y gstreamer1.0-plugins-{bad,base,good,ugly}
RUN apt-get install -y gstreamer1.0-alsa python-dev
RUN apt-get install -y python3-dbus
#libs for cryptography
RUN apt install -y build-essential libssl-dev libffi-dev python-dev

RUN mkdir -p /home/pi/evo-track/gui

ADD . /home/pi/evo-track/gui

RUN /home/pi/evo-track/gui/install/install.sh
#RUN /home/pi/evo-track/gui/install/python-install.sh

RUN pip3 -version

RUN pip3 install -r /home/pi/evo-track/gui/requirements.txt

CMD echo "hi!"