version: '3.2'

services:
  node:
#    image: "evo-track/ingress-server"
    build:
      dockerfile: ../../docker/ingress-server/Dockerfile  # need to go from context back to docker folder
      context: ../../ingress/server
    ports:
      - "3000:3000"
    volumes:
      # FOR LIVE UPDATES
      - ../../ingress/server/src:/app/src
      - ../../ingress/server/app.js:/app/app.js
      - ../../ingress/server/config.js:/app/config.js
      - ../../ingress/server/credentials.json:/app/credentials.json
      - ../../ingress/server/token.json:/app/token.json
      - node-sync:/other-app

volumes:
  node-sync:
    external: true